controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: True

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    robot_hand_controller:
      type: position_controllers/GripperActionController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

robot_arm_controller:
  ros__parameters:
    use_sim_time: True
    joints:
      - base_waist_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

robot_hand_controller:
  ros__parameters:
    use_sim_time: True
    joint: gripper1_joint
    action_monitor_rate: 20.0


diff_drive_controller:
  ros__parameters:
    use_sim_time: True
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.297
    wheel_radius: 0.033
    use_stamped_vel: false
