publisher_forward_position_controller:
  ros__parameters:

    wait_sec_between_publish: 5
    publish_topic: "/forward_position_controller/commands"

    goal_names: ["pos1", "pos2", "pos3", "pos4", "pos5", "pos6", "pos7"]
    pos0: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pos1: [ 0.4, 0.0, 0.4, 0.0, 0.2, 0.2]
    pos2: [ 0.8, 0.0, 0.8, 0.0, 0.4, 0.4]
    pos3: [ 0.4, 0.0, 1.0, 0.0, 0.6, 0.6]
    pos4: [ 0.0, 0.0, 0.8, 0.0, 0.4, 0.4]
    pos5: [-0.4, 0.0, 0.4, 0.0, 0.2, 0.2]
    pos6: [-0.8, 0.0, 0.2, 0.0, 0.0, 0.0]
    pos7: [-0.4, 0.0, 0.0, 0.0, 0.0, 0.0]
