controller_manager:
  ros__parameters:
    update_rate: 10
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_traj:
      type: joint_trajectory_controller/JointTrajectoryController

    robot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.297
    wheel_radius: 0.033
    use_stamped_vel: false

robot_arm_controller:
  ros__parameters:
    joints:
      - base_waist_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
      - gripper1_joint
      - gripper2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true