# Default initial positions for robot's ros2_control fake system

initial_positions:
  base_waist_joint: 0
  elbow_joint: 0
  gripper1_joint: 0
  gripper2_joint: 0
  shoulder_joint: 0
  wrist_joint: 0